/**
 * core/tts.js — Text-to-Speech for TerminalForge (Node.js)
 *
 * Speaks agent responses and system announcements using macOS `say`.
 * Optionally uses ElevenLabs for a higher-quality voice (ELEVENLABS_API_KEY required).
 *
 * Features:
 *   - Cleans markdown / code blocks / tool call output before speaking
 *   - Truncates long responses to the nearest sentence break (~400 chars)
 *   - Interrupts the current utterance when a new one starts
 *   - Non-blocking — fire-and-forget, TUI stays responsive
 *
 * Public API:
 *   speak(text, opts?)      — speak text aloud (async, non-blocking)
 *   stopSpeaking()          — kill current utterance immediately
 *   cleanForSpeech(text)    — strip markdown, return clean prose
 *
 * Config via environment (all optional):
 *   TTS_PROVIDER  — "say" (default) | "elevenlabs"
 *   TTS_VOICE     — macOS voice name (default: "Alex") or ElevenLabs voice ID
 *   TTS_RATE      — words per minute for `say` (default: 185)
 *   TTS_MAX_CHARS — max chars spoken per response (default: 420)
 */

import { spawn, execSync } from 'child_process';
import createDebug from 'debug';

const debug = createDebug('tf:voice');

// ── Defaults ──────────────────────────────────────────────────────────────────
// "Alex" is the clearest built-in macOS voice. Alternatives: Samantha, Daniel,
// Tom, Evan, Fred (most robotic). Run `say -v ?` to list all installed voices.
const DEFAULT_VOICE    = process.env.TTS_VOICE     || 'Alex';
const DEFAULT_RATE     = parseInt(process.env.TTS_RATE     || '185', 10);
const DEFAULT_MAX_CHARS = parseInt(process.env.TTS_MAX_CHARS || '420', 10);

// ── Text cleaning ─────────────────────────────────────────────────────────────

/**
 * Strip markdown, code, tool-call output and URLs from text.
 * Returns clean prose suitable for speech synthesis.
 */
export function cleanForSpeech(text) {
  if (!text) return '';
  let s = text;

  // Remove fenced code blocks entirely — code is unreadable when spoken
  s = s.replace(/```[\s\S]*?```/g, '');
  // Remove inline code
  s = s.replace(/`[^`\n]+`/g, '');
  // Remove tool-call preview lines generated by formatToolCall / formatToolResult
  // e.g.  `read_file(path: src/index.js)`
  s = s.replace(/^`[a-z_]+\([^)]*\)`\s*$/gm, '');
  // Remove markdown bold/italic markers — keep the inner text
  s = s.replace(/\*\*(.+?)\*\*/gs, '$1');
  s = s.replace(/\*(.+?)\*/gs,     '$1');
  s = s.replace(/__(.+?)__/gs,     '$1');
  s = s.replace(/_([^_\n]+)_/gs,   '$1');
  // Remove heading markers
  s = s.replace(/^#{1,6}\s+/gm, '');
  // Convert markdown links to their label only
  s = s.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');
  // Remove bare URLs
  s = s.replace(/https?:\/\/\S+/g, '');
  // Remove blockquote markers
  s = s.replace(/^\s*>\s*/gm, '');
  // Remove bullet / ordered list markers (keep text)
  s = s.replace(/^\s*[-*+]\s+/gm, '');
  s = s.replace(/^\s*\d+\.\s+/gm,  '');
  // Remove horizontal rules
  s = s.replace(/^[-*_]{3,}\s*$/gm, '');
  // Collapse excess blank lines and trim
  s = s.replace(/\n{3,}/g, '\n\n');
  return s.trim();
}

/**
 * Truncate cleaned text to at most maxChars, breaking at a sentence boundary.
 */
function truncateAtSentence(text, maxChars) {
  if (text.length <= maxChars) return text;
  const cut      = text.slice(0, maxChars);
  const lastBreak = Math.max(
    cut.lastIndexOf('. '),
    cut.lastIndexOf('! '),
    cut.lastIndexOf('? '),
    cut.lastIndexOf('.\n'),
  );
  // Only use the sentence break if it's past 40% of the limit (avoids cutting too short)
  if (lastBreak > maxChars * 0.4) {
    return cut.slice(0, lastBreak + 1).trim();
  }
  return cut.trim();
}

// ── macOS `say` ───────────────────────────────────────────────────────────────

let _currentPid = null; // PID of current `say` or `afplay` process

/**
 * Speak using macOS `say` (non-blocking, async).
 * Caller is responsible for calling stopSpeaking() first if needed.
 */
function _speakSay(text, voice, rate) {
  debug('say -v %s -r %d | %d chars', voice, rate, text.length);
  const child = spawn('say', ['-v', voice, '-r', String(rate), text], {
    stdio: 'ignore',
  });
  _currentPid = child.pid ?? null;
  child.on('exit',  () => { _currentPid = null; });
  child.on('error', (err) => {
    debug('say error: %s', err.message);
    _currentPid = null;
  });
}

// ── ElevenLabs ────────────────────────────────────────────────────────────────

async function _speakElevenLabs(text, voiceId) {
  const apiKey = process.env.ELEVENLABS_API_KEY;
  if (!apiKey) {
    debug('ELEVENLABS_API_KEY not set — falling back to say');
    _speakSay(text, DEFAULT_VOICE, DEFAULT_RATE);
    return;
  }

  try {
    const id = voiceId || 'EXAVITQu4vr4xnSDxMaL';   // "Bella" — clear, pleasant
    const resp = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${id}/stream`,
      {
        method:  'POST',
        headers: { 'xi-api-key': apiKey, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          text,
          model_id:      'eleven_turbo_v2',
          voice_settings: { stability: 0.5, similarity_boost: 0.75 },
        }),
      },
    );

    if (!resp.ok) throw new Error(`ElevenLabs HTTP ${resp.status}`);

    const { tmpdir }              = await import('os');
    const { join }                = await import('path');
    const { writeFile, unlink }   = await import('fs/promises');

    const buf = Buffer.from(await resp.arrayBuffer());
    const tmp = join(tmpdir(), `forge-tts-${Date.now()}.mp3`);
    await writeFile(tmp, buf);

    const child = spawn('afplay', [tmp], { stdio: 'ignore' });
    _currentPid = child.pid ?? null;
    child.on('exit', () => {
      _currentPid = null;
      unlink(tmp).catch(() => {});
    });
    child.on('error', () => {
      _currentPid = null;
      _speakSay(text, DEFAULT_VOICE, DEFAULT_RATE); // fallback
    });

    debug('elevenlabs → afplay pid=%d', _currentPid);
  } catch (err) {
    debug('ElevenLabs TTS failed (%s) — falling back to say', err.message);
    _speakSay(text, DEFAULT_VOICE, DEFAULT_RATE);
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Stop any currently-playing speech immediately.
 * Call this when a new user message is submitted so FORGE stops mid-sentence.
 */
export function stopSpeaking() {
  if (_currentPid) {
    try { process.kill(_currentPid, 'SIGTERM'); } catch { /* already gone */ }
    _currentPid = null;
  }
  // Kill any stray `say` / `afplay` the OS is still holding
  try { execSync('pkill -x say   2>/dev/null || true', { stdio: 'ignore' }); } catch { /* ok */ }
  try { execSync('pkill -x afplay 2>/dev/null || true', { stdio: 'ignore' }); } catch { /* ok */ }
}

/**
 * Speak text aloud.
 *
 * The text is automatically cleaned (markdown stripped) and truncated.
 * Any currently-playing speech is interrupted first.
 *
 * @param {string} text
 * @param {object} [opts]
 * @param {string}  [opts.provider]   "say" (default) | "elevenlabs"
 * @param {string}  [opts.voice]      macOS voice name / ElevenLabs voice ID
 * @param {number}  [opts.rate]       Words per minute (say only)
 * @param {number}  [opts.maxChars]   Max chars to speak (default 420)
 * @param {boolean} [opts.skipClean]  Skip markdown stripping (text is already clean)
 * @param {boolean} [opts.interrupt]  Stop current speech first (default: true)
 */
export function speak(text, opts = {}) {
  if (!text?.trim()) return;

  const provider  = opts.provider  ?? (process.env.TTS_PROVIDER || 'say');
  const voice     = opts.voice     ?? DEFAULT_VOICE;
  const rate      = opts.rate      ?? DEFAULT_RATE;
  const maxChars  = opts.maxChars  ?? DEFAULT_MAX_CHARS;
  const interrupt = opts.interrupt ?? true;

  // Stop current speech ONCE here — _speakSay / _speakElevenLabs do NOT call
  // stopSpeaking themselves, so there is no double-kill.
  if (interrupt) stopSpeaking();

  const cleaned = opts.skipClean ? text.trim() : cleanForSpeech(text);

  // Smart fallback when cleaning strips everything (common with Ollama code-only
  // responses — the model returns a bare code block with no prose around it).
  if (!cleaned) {
    const raw = text.trim();
    let fallback = '';
    if (raw.includes('```'))        fallback = 'Here is the code. Check the screen for the full output.';
    else if (raw.startsWith('`'))   fallback = 'Done. Check the screen for the result.';
    else if (raw.length > 0)        fallback = 'Response complete. Check the screen for details.';
    if (fallback) {
      debug('speak: cleaned empty — using fallback');
      _speakSay(fallback, voice, rate);
    }
    return;
  }

  const spoken = truncateAtSentence(cleaned, maxChars);
  debug('speak [%s] %d → %d chars: %s…', provider, cleaned.length, spoken.length, spoken.slice(0, 60));

  if (provider === 'elevenlabs') {
    _speakElevenLabs(spoken, voice).catch(err => debug('elevenlabs async error: %s', err.message));
  } else {
    _speakSay(spoken, voice, rate);
  }
}
